# Generated by Django 4.2.5 on 2024-01-09 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=50)),
                ('productid', models.CharField(max_length=50)),
                ('userid', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('tprice', models.CharField(max_length=50)),
                ('quntity', models.CharField(default=' ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Blog1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Categ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='cat_img')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=50)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=6)),
                ('payment', models.CharField(max_length=50)),
                ('transactionid', models.CharField(max_length=50)),
                ('tprice', models.CharField(max_length=30)),
                ('quntity', models.CharField(max_length=10)),
                ('city', models.CharField(default=' ', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Userregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('address', models.TextField(default=' ')),
                ('image', models.ImageField(default=' ', upload_to='cat')),
                ('otp', models.CharField(default=' ', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='wandersignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=50)),
                ('image', models.ImageField(upload_to='wander')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=50)),
                ('Product_price', models.IntegerField()),
                ('Product_brand', models.CharField(max_length=50)),
                ('Product_quntity', models.CharField(max_length=50)),
                ('Product_image', models.ImageField(upload_to='product_image')),
                ('Product_disc', models.CharField(max_length=50)),
                ('Product_categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.categ')),
            ],
        ),
    ]
