# Generated by Django 4.2.5 on 2023-09-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_musician_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
