# Generated by Django 4.2.5 on 2023-09-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_categ'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Blog1',
        ),
    ]
