# Generated by Django 4.2.5 on 2023-09-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_userregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='image',
            field=models.ImageField(default=' ', upload_to='cat_e'),
        ),
    ]
