# Generated by Django 4.2.5 on 2023-09-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_userregister_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='image',
        ),
        migrations.AddField(
            model_name='userregister',
            name='address',
            field=models.TextField(default=' '),
        ),
    ]
