# Generated by Django 4.2.5 on 2023-10-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_userregister_image_userregister_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='image',
            field=models.ImageField(default=' ', upload_to='cat_e'),
        ),
    ]
