# Generated by Django 4.2.5 on 2023-10-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_userregister_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='image',
            field=models.ImageField(default=' ', upload_to='cat'),
        ),
    ]
