# Generated by Django 4.2.5 on 2023-10-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_userregister_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=50)),
                ('Product_price', models.IntegerField(max_length=30)),
                ('Product_brand', models.CharField(max_length=50)),
                ('Product_quntity', models.CharField(max_length=50)),
                ('Product_image', models.ImageField(upload_to='product_image')),
                ('Product_disc', models.CharField(max_length=50)),
                ('Product_categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.categ')),
            ],
        ),
    ]
