# Generated by Django 4.2.5 on 2023-10-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='wandersignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=50)),
                ('image', models.ImageField(upload_to='wander')),
            ],
        ),
    ]
