# Generated by Django 4.2.5 on 2023-10-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_wandersignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=50)),
                ('productid', models.CharField(max_length=50)),
                ('userid', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('tprice', models.CharField(max_length=50)),
            ],
        ),
    ]
