# Generated by Django 4.2.5 on 2023-10-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_addcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcart',
            name='quntity',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
